### ISSUE TITLE
Add effectful to stackage

### ISSUE THREAD

**Issue by lukasz-golebiewski** [haskell-effectful/effectful#104]
Without this it is necessary to pin the version in stack.yaml extra-deps which is inconvenient

**Comment by arybczak** [comment]
I was reluctant to do this since IIUC then you become a maintainer and have a soft obligation to bump versions.

I'm not using stack and I am sure I'll forget to do that on subsequent releases. @lukasz-golebiewski perhaps you're interested in adding it? 🙂

**Comment by lukasz-golebiewski** [comment]
Sure, I'll give it a go!

**Comment by kutyel** [comment]
@arybczak it was merged! Maybe this can be closed now :)
