### ISSUE TITLE
[Question] Interpreter for multiple effects

### ISSUE THREAD

**Issue by jonathanmoregard** [haskell-effectful/effectful#114]
I don't know if this belong here, but I ran into some issues implementing an interpreter that interprets two effects at a time.
I tried to understand if it was possible to do with `reinterpret`, and if any of the unlifting strategies were relevant, but I struggled to make sense of things. I generally find this lib easy to work with, but I think I lack some mental models for the interpreter implementations.

The solution I ended up with isn't very satisfying, is it possible to do the following in another way?

```haskell
modelScenario :: forall a. [Event a] -> Model a
modelScenario events = runPureEff $ pureInterpreter scenario
  where
    scenario :: Eff (Event_Write a : Event_Read a : State [Event a] : '[]) (Model a)
    scenario = do
      forM_ events DomainThingy.writeEvent
      DomainThingy.getModel

pureInterpreter :: forall a b es. Eff (Event_Write a : Event_Read a : State [Event a] : es) b -> Eff es b
pureInterpreter = State.evalState [] . interpretRead . interpretWrite
  where
    interpretWrite :: Eff (Event_Write a : Event_Read a : State [Event a] : es) b -> Eff (Event_Read a : State [Event a] : es) b
    interpretWrite = interpret $ \_ -> \case
      DomainThingy.WriteEvent e -> State.modify (e :)
    interpretRead :: Eff (Event_Read a : State [Event a] : es) b -> Eff (State [Event a] : es) b
    interpretRead = interpret $ \_ -> \case
      DomainThingy.ReadEvents -> State.get
```

**Comment by Nexmean** [comment]
If you want to hide `State [Event a]` you can use [`inject`](https://hackage.haskell.org/package/effectful-core-2.2.1.0/docs/Effectful.html#v:inject), but you'll need additional constraint [`Subset`](https://hackage.haskell.org/package/effectful-core-2.2.1.0/docs/Effectful.html#t:Subset)

**Comment by arybczak** [comment]
@Nexmean is right, `inject` works. Unfortunately at the moment you will need to add the appropriate `Subset` constraint because it only works for fully known lists.

I have a plan to generalize `inject` so that it automatically resolves for lists that share a common suffix, so then you will be able to write

```haskell
hideState :: Eff (Event_Write a : Event_Read a : State [Event a] : es) r -> Eff (Event_Write a : Event_Read a : es) r
hideState = inject
```

and use this to hide the State without the need of `Subset`.

**Comment by arybczak** [comment]
You can also write `reinterpret2` that does what you want yourself.

```haskell
reinterpret2
  :: (DispatchOf e1 ~ Dynamic, DispatchOf e2 ~ Dynamic)
  => (Eff handlerEs a -> Eff es b)
  -> EffectHandler e1 handlerEs
  -> EffectHandler e2 handlerEs
  -> Eff (e1 : e2 : es) a
  -> Eff            es  b
reinterpret2 runHandlerEs handler1 handler2 m = unsafeEff $ \es -> do
  (`unEff` es) . runHandlerEs . unsafeEff $ \handlerEs -> do
    (`unEff` es) $ runHandler (Handler handlerEs handler2)
                 $ runHandler (Handler handlerEs handler1)
                 $ m
```

You'll need to import `Effectful.Internal.Monad` for this though.

Perhaps it's worth to include this in the library for up to `reinterpret5` :thinking:

**Comment by arybczak** [comment]
@jonathanmoregard is `reinterpret2` what you were looking for?

**Comment by jonathanmoregard** [comment]
I haven't tried it out, but it looks like it!
This turned out to not be needed atm, but I can repro where I was if it helps you.

Adding `reinterpretN` for n upt o 5 seems like a good idea

**Comment by arybczak** [comment]
I decided to go with the route of generalizing `inject` for now as it seems cleaner and is more general than `reinterpretN` variants.
