### ISSUE TITLE
Thunk retention in Env

### ISSUE THREAD

**Issue by Kleidukos** [haskell-effectful/effectful#115]
While profiling an application using `effectful`, I came across the following in the report:

![Screenshot 2022-12-01 at 21-13-33 eventlog2html - Heap Profile](https://user-images.githubusercontent.com/29253044/205150676-9d036438-b3fb-4d45-9cee-a7d627f16262.png)

It's not tragic but perhaps would benefit from some investigation?

**Comment by arybczak** [comment]
It looks like the only thing these thunks can be are applications of `toAny` since at these locations effect datatypes are evaluated with `seq`.

Can you try with #116 to see if it fixes the problem?
