### ISSUE TITLE
How to generate benchmark graphs, and for all libraries?

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-effectful/effectful#129]
Could someone please help me generate benchmark graphs, and for all libraries? Currently I only know how to go to the `effectful` subdirectory and run `cabal run bench`. But that only runs benchmarks for `reference` and `effectful`, and it doesn't seem to generate graphs.

I guess I have to define `VERSION_freer_simple` in `CPP`  somehow, and perhaps pass a flag to `testy-bench`/`criterion` to generate graphs? What' the right way of doing that?

**Comment by arybczak** [comment]
For including foreign libraries in benchmarks put into your `cabal.project.local`

```
package effectful
  flags: +benchmark-foreign-libraries
```

As for graphs, see `cabal run bench -- --help`, there's a `--svg` option.

**Comment by tomjaguarpaw** [comment]
Yes, it works! Thank you very much for a very quick response.
