### ISSUE TITLE
[Question] Scoped effects in effectful

### ISSUE THREAD

**Issue by googleson78** [haskell-effectful/effectful#134]
Hi!

Does `effectful` support something like `polysemy`'s [Scoped](https://www.tweag.io/blog/2022-01-05-polysemy-scoped/)?

If not, is there a way to handle having state transactions *in* my business logic in a type safe way, i.e.
* I should not be able to use my "stateful effect" outside a transaction
* I should not have to leak the implementation of the transaction (e.g. acquiring an sql connection from a pool)

?

**Comment by arybczak** [comment]
> Does effectful support something like polysemy's [Scoped](https://www.tweag.io/blog/2022-01-05-polysemy-scoped/)?

There is no `Scoped` in `effectful` at the moment, but I'm pretty sure it can be written.

**Comment by arybczak** [comment]
@googleson78 I've read a bit about this.

Do I understand correctly that `Scoped` is basically a way to abstract away running a dynamically dispatched effect into a dynamically dispatched effect itself?
