### ISSUE TITLE
GHC panic when using effectful-plugin without effectful-core

### ISSUE THREAD

**Issue by dark-ether** [haskell-effectful/effectful#142]
when i have in my dependencies effectful and effectful-plugin without effectful-core. trying to compile my project with `cabal build` will cause a GHC panic.
i am using, cabal-install version 3.8.1.0 compiled using version 3.8.1.0 of the Cabal library, The Glorious Glasgow Haskell Compilation System, version 9.2.4.
[ghcpanic.zip](https://github.com/haskell-effectful/effectful/files/10785726/ghcpanic.zip)
here is a zip file containing a minimal project to reproduce the problem

**Comment by Kleidukos** [comment]
@dark-ether hi, and thank you for this report. :) We're aware of this, please see https://github.com/haskell-effectful/effectful/issues/86 for more information :)

**Comment by dark-ether** [comment]
ok, should i close the issue?

**Comment by dark-ether** [comment]
i think it will be unnecessary, i already found a workaround and the issue mentions it will give a better error message, to guide others to the workaround
