### ISSUE TITLE
Variant of runError that allows handling errors

### ISSUE THREAD

**Issue by mkleczek** [haskell-effectful/effectful#152]
Right now even if we catch errors inside `runError` or `runErrorNoCallStack` we still have to deal with them outside of the effect handler as it returns `Either e a`.

A variant taking an error handler and returning `a` would be very convenient.

Looks like there is already a discussion about this topic: https://github.com/haskell-effectful/effectful/discussions/149

**Comment by mkleczek** [comment]
Actually - after a bit of thought - I think Error effect API might be better if:
* the effect itself would only provide one operation: throwError
* various catch variants would discharge it

**Comment by ocharles** [comment]
> I don't think so slightly_smiling_face If runError replaces catchError, then catching errors will no longer be possible once you are in Eff es where Error e :> es (i.e. its position in the stack is unknown), which is a significant limitation.

Hmm, is that true? This is just like using `runExceptT` to dispatch a `MonadError` constraint. If you have something that is `forall es. Error e :> es`, then you can just call `runErrorWith` on and you'll be left with just `forall es`. So in this case, it doesn't matter where `Error e` is in the stack.

**Comment by arybczak** [comment]
> Hmm, is that true?

You're right, it's not. It will work, but it will duplicate the `Error` effect, which is still a bit confusing.

Also, if there's no `CatchError` operation in the dynamic `Error`, you can't customize it (not sure what customizations could be made there, but still).

To summarize, I think having both `runErrorWith` and `catchError` is not worse than having only `runErrorWith` :thinking:

**Comment by mkleczek** [comment]
I would say catchError name and signature don't really match and are misleading. Normally catching errors means the error is handled - and the signature should reflect that. Of course - you can re-throw the error but then it only means handler requires an error effect. If you don't re-throw then you must return something sensible.

What possibly can be added is `onError :: Error e :> es => Eff es a -> (e -> Eff es ()) -> Eff es a` that can perform an action when error is thrown (not sure if this action should be restricted to be non-throwing though)

**Comment by ocharles** [comment]
> You're right, it's not. It will work, but it will duplicate the Error effect, which is still a bit confusing.

What do you mean? `runErrorWith` doesn't re-introduce `Error e :> es`, so where does duplication happen? You're just locally dispatching the `Error e` constraint.

**Comment by arybczak** [comment]
> runErrorWith doesn't re-introduce Error e :> es

Hmm, AFAICS it has to have a sig `runErrorWith :: (CallStack -> e -> Eff es a) -> Eff (Error e : es) a -> Eff es a`, so it does re-introduce it.

If it didn't change `es`, then it would be `runErrorWith :: Error e :> es => (CallStack -> e -> Eff es a) -> Eff es a -> Eff es a`, which is `handleError`. 

I see no other choice. You can't have the same `es` and the inner action have the `Error e :> es` constraint, but the outer not, right? :thinking:

**Comment by mkleczek** [comment]
I've implemented a prototype that would offer the following syntax (which I - coming from Java - find the most natural):
```
temp :: Eff '[] ()
temp =
  do
    x <- throwError "sadfsdfaas"
    pure x -- I wonder if it is possible to do some type level trickery that this dead code is not possible
  `onError` (\(_ :: String) -> pure ()) -- do something on error ie. logging etc.
  `wrapError` const @Int @String 5 -- wrap error in another error
  `catchError` (\(_ :: Int) -> throwError "sssss") -- discharge Error Int throwing Error String
  `catchError` (\(_ :: String) -> pure ()) -- discharge Error String handling any nested throwError String

```

**Comment by fonghou** [comment]
> > runErrorWith doesn't re-introduce Error e :> es
> 
> Hmm, AFAICS it has to have a sig `runErrorWith :: (CallStack -> e -> Eff es a) -> Eff (Error e : es) a -> Eff es a`, so it does re-introduce it.

`Error e` is not in return type's effect list `es` anymore since it's already discharged by (Callback -> e -> Eff es a). What do you mean "it does re-indroduce it"?

> 
> If it didn't change `es`, then it would be `runErrorWith :: Error e :> es => (CallStack -> e -> Eff es a) -> Eff es a -> Eff es a`, which is `handleError`.
> 
> I see no other choice. You can't have the same `es` and the inner action have the `Error e :> es` constraint, but the outer not, right? 🤔

Do you mean this type signture can't be written with effectful?

`catchError :: (Error e :> InEs, InEs ~ Error e : outEs) => Eff inEs a -> (Callback -> e -> Eff outEs a) -> Eff outEs a`

Current catchError sounds more like catchErrorWithRethrow, which is mkleczek's main point. However, I'm not sure his catchError' below has the right type either because `Error e` must be head of inner effect list.

**Comment by arybczak** [comment]
> Do you mean this type signture can't be written with effectful?
>
> catchError :: (Error e :> InEs, SetRemove inEs (Error e) outEs ) => Eff inEs a -> (e -> Eff outEs a) -> Eff outEs a

This has more to do with Haskell than effectful specifically. How do you implement `SetRemove`?

**Comment by fonghou** [comment]
> > Do you mean this type signture can't be written with effectful?
> > catchError :: (Error e :> InEs, SetRemove inEs (Error e) outEs ) => Eff inEs a -> (e -> Eff outEs a) -> Eff outEs a
> 
> This has more to do with Haskell than effectful specifically. How do you implement a working `SetRemove`?

So it's impossible to write SetRemove in typeclass, would it be possible in type family?

`catchError :: (Error e :> InEs, outEs ~ SetRemove inEs (Error e)) => Eff inEs a -> (e -> Eff inEs a) -> Eff outEs a`

**Comment by mkleczek** [comment]
> > Do you mean this type signture can't be written with effectful?
> > catchError :: (Error e :> InEs, SetRemove inEs (Error e) outEs ) => Eff inEs a -> (e -> Eff outEs a) -> Eff outEs a
> 
> This has more to do with Haskell than effectful specifically. How do you implement a working `SetRemove`?

How about:
```
catchError :: forall a e ines outes. (Subset outes ines, Error e :> ines) => Eff ines a -> (e -> Eff outes a) -> Eff outes a
```

**Comment by fonghou** [comment]
I tried this...

```
type family es :- e :: [Effect] where
  '[] :- _ = '[]
  (x : xs) :- x = xs
  xs :- _ = xs

-- | Handle errors of type @e@.
runError ::
  forall e ines outes a.
  (Error e :> ines, outes ~ (ines :- (Error e))) =>
  -- | The inner computation.
  Eff ines a ->
  Eff outes (Either (CallStack, e) a)
runError m = unsafeEff $ \es0 -> mask $ \unmask -> do
  eid <- newErrorId
  es <- consEnv (Error @e eid) dummyRelinker es0
  r <- tryErrorIO unmask eid es `onException` unconsEnv es
  unconsEnv es
  pure r
 where
  tryErrorIO unmask eid es =
    try (unmask $ unEff m es) >>= \case
      Right a -> pure $ Right a
      Left ex ->
        tryHandler ex eid (\cs e -> Left (cs, e)) $
          throwIO ex
```
However, got following error.  It seems current runError code  **_requires_** a class instance ‘ines ~ (Error e : outes)’ (by consEnv or unconsEnv?), but (Error e :> ines, outes ~ (ines :- Error e)) states (Error e) can be anywhere in the stack. My guess is that the code needs to be modified to use an instance of reifyIndex that can remove (Error e) handler from (Env ines) anywhere, and produce (Env outes). Beyond my knowledage at this point.

```
src/Effectful/Error/Static.hs:130:30-31: error: [GHC-25897]
    • Could not deduce ‘ines ~ (Error e : outes)’
      from the context: (Error e :> ines, outes ~ (ines :- Error e))
        bound by the type signature for:
                   runError ∷ ∀ e (ines ∷ [Effect]) (outes ∷ [Effect]) a.
                              (Error e :> ines, outes ~ (ines :- Error e)) ⇒
                              Eff ines a → Eff outes (Either (CallStack, e) a)
        at src/Effectful/Error/Static.hs:(121,1)-(126,37)
      Expected: Env ines
        Actual: Env (Error e : outes)
      ‘ines’ is a rigid type variable bound by
        the type signature for:
          runError ∷ ∀ e (ines ∷ [Effect]) (outes ∷ [Effect]) a.
                     (Error e :> ines, outes ~ (ines :- Error e)) ⇒
                     Eff ines a → Eff outes (Either (CallStack, e) a)
        at src/Effectful/Error/Static.hs:(121,1)-(126,37)
    • Relevant bindings include
        es ∷ Env (Error e : outes)
          (bound at src/Effectful/Error/Static.hs:129:3)
        tryErrorIO ∷ (IO a → IO a)
                     → ErrorId → Env ines → IO (Either (CallStack, e) a)
          (bound at src/Effectful/Error/Static.hs:134:3)
        (Some bindings suppressed; use -fmax-relevant-binds=N or -fno-max-relevant-binds)
    |
130 |   r <- tryErrorIO unmask eid es `onException` unconsEnv es
    |                              ^^
```

**Comment by eddiemundo** [comment]
> Unfortunately, I seem not to understand how it should work. The following piece of code (catchErrorIO copied from Effectful.Static.Error):
> 
> ```
> catchError' :: forall e es a. Eff (Error e : es) a -> (e -> Eff es a) -> Eff es a
> catchError' eff handler = unsafeEff $ \es0 -> do
>   eid <- newErrorId
>   catchErrorIO eid $
>     bracket
>       (consEnv (Error @e eid) dummyRelinker es0)
>       unconsEnv
>       (unEff eff)
>     (\cs e -> unEff (handler e) es0)
> ```
> 
> does not work as expected - looks like handler effect is not executed for some reason (it does have the same Error e effect)

I was just wondering what's wrong with the naive
```
runErrorWith :: Eff (Error e : es) a -> (e -> Eff es a) -> Eff es a
runErrorWith action f = do
  result <- runErrorNoCallStack action
  case result of
    Left e -> f e
    Right a -> pure a
```

**Comment by fonghou** [comment]
> > Unfortunately, I seem not to understand how it should work. The following piece of code (catchErrorIO copied from Effectful.Static.Error):
> > ```
> > catchError' :: forall e es a. Eff (Error e : es) a -> (e -> Eff es a) -> Eff es a
> > catchError' eff handler = unsafeEff $ \es0 -> do
> >   eid <- newErrorId
> >   catchErrorIO eid $
> >     bracket
> >       (consEnv (Error @e eid) dummyRelinker es0)
> >       unconsEnv
> >       (unEff eff)
> >     (\cs e -> unEff (handler e) es0)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > does not work as expected - looks like handler effect is not executed for some reason (it does have the same Error e effect)
> 
> I was just wondering what's wrong with the naive
> 
> ```
> runErrorWith :: Eff (Error e : es) a -> (e -> Eff es a) -> Eff es a
> runErrorWith action f = do
>   result <- runErrorNoCallStack action
>   case result of
>     Left e -> f e
>     Right a -> pure a
> ```


Nothing wrong with it. We're just wondering if effectul can provide a catch handler that has the semantics https://www.parsonsmatt.org/2020/10/27/plucking_in_plucking_out.html, which means type signature should be something like

```
catchError :: (Error e :> inEs, SetRemove inEs (Error e) outEs) => Eff inEs a -> (e -> Eff outEs a) -> Eff outEs a
```

then the code above doesn't type check anymore.

**Comment by arybczak** [comment]
> We're just wondering if effectul can provide a catch handler that has the semantics https://www.parsonsmatt.org/2020/10/27/plucking_in_plucking_out.html, which means type signature should be something like
>
>catchError :: (Error e :> inEs, SetRemove inEs (Error e) outEs) => Eff inEs a -> (e -> Eff outEs a) -> Eff outEs 

I don't see anywhere in this blog post a function with signature resembling what you wrote here :thinking: 

In fact, `catch :: App r (lil || rest) a -> (lil -> App r rest a) -> App r rest a` from the blog post is pretty much the same thing as `runErrorWith :: Eff (Error e : es) a -> (e -> Eff es a) -> Eff es a`.

**Comment by fonghou** [comment]
Hi @arybczak, below is copy-and-paste from that blog post. The type of first catch looks like effectful runError.  My catchError looks like second "The Correct type of catch" below.

The problem with catch is that it doesn’t change the error set at all.

```
catch
  :: Either e a
  -> (e -> Either e a)
  -> Either e a
```

There is no type-level evidence that anything has changed. Alexis King would call this [validation, not parsing](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/).

The Correct type of catch is something like:

```
catch
  :: forall input small rest
   . ( Contains small input
     , rest ~ Delete small input 
     )
  => Either input a
  -> (small -> Either rest a)
  -> Either rest a
```

The big difference here is that the small type of problem has been handled, and we’re only left with the rest.

**Comment by arybczak** [comment]
While this might be a "correct" type signature on the conceptual level, it doesn't matter if it won't compile or behave the way you expect it to.

Try to implement this and you'll understand what I mean. Ignore the implementation, just write down type signatures and use `undefined` as implementation.

Then try to use this function in the `Eff` monad with both monomorphic and polymorphic effect stack and see what happens.

**Comment by fonghou** [comment]
That was what I tried to do in previous post https://github.com/haskell-effectful/effectful/issues/152#issuecomment-1568926593 for the "correct" tryError type, trying to use runError code as evidence but failed. Do you think my comments there make sense at all?

Yes,  undefined typechecks (e.g. catchError below).  But the difficulty still resides in whether effectful's design allows an instance of reifyIndex that discharges (Error e) in the **middle** of term level Env stack. Are you implying that it's impossible?

```
catchError ::
  forall e ines outes a.
  (Error e :> ines, outes ~ (ines :- (Error e))) =>
  -- | The inner computation.
  Eff ines a ->
  -- | A handler for errors in the inner computation.
  (CallStack -> e -> Eff outes a) ->
  Eff outes a
catchError' = undefined
```

**Comment by arybczak** [comment]
You didn't do this part:

> Then try to use this function in the Eff monad with both monomorphic and polymorphic effect stack and see what happens.
