### ISSUE TITLE
Overlapping instances on local State effects

### ISSUE THREAD

**Issue by smunix** [haskell-effectful/effectful#165]
Compiling the following code with ghc961, and ghc927 (using Nix)

```hs
import Effectful
import Effectful.Dispatch.Dynamic
import Effectful.State.Dynamic
import Effectful.TH

import Data.Map (Map)
import Data.Map qualified as Map

-- | A Graph  effect on nodes of type a
data Graph a ∷ Effect where
  Node ∷ a → Graph a m ()

makeEffect ''Graph

run
  ∷ ∀ a es r nid a2nid nid2a
   . ( nid ~ Int
     , a2nid ~ Map a nid
     , nid2a ~ Map nid a
     , Ord a
     )
  ⇒ Eff (Graph a : es) r
  → Eff es r
run = reinterpret
  ( evalStateLocal @nid 0
      . evalStateLocal @a2nid Map.empty
      . evalStateLocal @nid2a Map.empty
  )
  \env → \case
    Node a → runNode a
  where
    runNode ∷ ∀ es m. (m ~ Eff es, State a2nid :> es, State nid :> es) ⇒ a → m ()
    runNode a =
      gets @a2nid (Map.lookup a) >>= \case
        Just {} → return ()
        Nothing {} →  modify @nid succ
```

It fails with fails with Overlapping instances

```
    instance (e :> es) => e :> (x : es)
    instance [overlapping] e :> e (e : es)
```
Here's the [full compilation output](https://github.com/smunix/haskell-effectful-issue-01/blob/main/output.log)

To reproduce, I have created a repository that can be found [here](https://github.com/smunix/haskell-effectful-issue-01). 

You can either clone this repo or, if you are using nix, simply run:
```sh
$> nix develop 'github:smunix/haskell-effectful-issue-01' -L
```
A `.cabal` file is also provided; so `cabal build` could be used as well.

I have only attempted this on `aarch64-linux`, so your mileage may vary if you're on a different platform.

**Comment by arybczak** [comment]
```
Overlapping instances for State (Map a Int)
                                :> (State (Map Int a) : State (Map a Int) : State Int : es)
        arising from a use of ‘runNode’
```

This is because GHC cannot know in advance what effect to select given these types. If `a ~ Int`, it would pick `State (Map Int a)`, but if e.g. `a ~ Bool`, it would pick ` State (Map a Int)`. You need newtypes for these maps.

**Comment by smunix** [comment]
Ah, thanks @arybczak ! That makes sense. Using the product of the states is another alternative I can do; `State (Map a int, Map Int a)`

I'll close this now
