### ISSUE TITLE
Make the initial release

### ISSUE THREAD

**Issue by arybczak** [haskell-effectful/effectful#20]
#17 was the last missing piece of the puzzle, all that remains now is some bikeshedding, documentation and a few more tests :slightly_smiling_face: 

Perhaps it would be good to separate `AsyncE` and `Resource` into a different package.

-----

UPDATE (23.01.22):

Left to do:

* [x] Add overview of the library to the `Effectful` module.
* [x] Document modules containing dynamic versions of `Error`, `Reader`, `State` and `Writer`.
* [x] Add tests for `Reader` and `Writer`.
* [x] Move the `Resource` effect to the `resourcet-effectful` package.
* [x] Add `effectful-th` for generation of effect operations as functions for dynamic effects with TH.

**Comment by mmhat** [comment]
I am really looking forward to that! I continued porting one of my RIO-based applications (it's a build system) to this library and I am quite happy with the results: The performance is basically the same, but the code structure improved a lot. So far for the first usage in the wild :smile: 

> Perhaps it would be good to separate `AsyncE` and `Resource` into a different package.

I vote for the `unliftio` approach: `effectful-core`, `effectful-async`, `effectful-resource` and `effectful` being the one with batteries included.

**Comment by arybczak** [comment]
> I am really looking forward to that! I continued porting one of my RIO-based applications (it's a build system) to this library and I am quite happy with the results: The performance is basically the same, but the code structure improved a lot. I didn't find any other bugs though. So far for the first usage in the wild smile

That's great to hear :+1: 

> I vote for the `unliftio` approach: `effectful-core` (and maybe `effectful-async`, `effectful-resource`) and `effectful` being the one with batteries included.

Yes, that sounds like a good approach to me. `effectful-core` for the core and `effectful` for other things. I think I'll mimic `unliftio` and include `async` in `effectful` since it's ubiquitous, but make a separate package for the `Resource` effect.

**Comment by mmhat** [comment]
> but make a separate package for the `Resource` effect.

Do you plan to reexport the `Resource` effect in `effectful`? IMHO it adds some value to the batteries-included version if we were shipping it with some kind of resource effect.

**Comment by mmhat** [comment]
Hm, what are the plans for the `Reader`/`State`/`Writer` effects? Should those live in `effectful` or `effectful-core`? Note that the tests for the `Async` effect require (some of) those. I guess that leaves us with three options:

1. The `Reader`/`State`/`Writer` effects stay in `effectful-core`.
2. We move those effects to `effectful` and test the Async effect there. IMHO going down that path would be something between "weird" and "wrong"...
3. Or maybe we should reconsider leaving the Async effect in `effectful-core` and strip down that library to a bare minimum, i.e. only leaving `Effectful.Handler` and `Effectful.Monad` as the public API and the `Effectful.Internal.*` as the private one. :thinking:

**Comment by arybczak** [comment]
A combination of 1 and 2 - everything that's currently in the repo except `Effectful.Async` and `Effectful.Resource` will be in `effectful-core`.

`Async` effect will be tested in the package that defines it (`effectful` most likely).

Besides that `effectful` will include wrappings for some parts of `base` and a few GHC boot deps, similar to `unliftio`.

`resourcet` is pretty specific, `unliftio` doesn't include it, so I'm leaning towards having a separate `effectful-resourcet` package for it not included in `effectful`.

**Comment by mmhat** [comment]
> A combination of 1 and 2 - everything that's currently in the repo except `Effectful.Async` and `Effectful.Resource` will be in `effectful-core`.

Ah, ok, now I got it. :smile:

**Comment by kozross** [comment]
Could we please get a release of `effectful-core`, @arybczak?

**Comment by arybczak** [comment]
Right, so the current status is that while from the technical side it's ready, parts of documentation are still missing.

I'd love to fill it in, but so far I was completely out of time :disappointed:

**Comment by arybczak** [comment]
I updated the OP with a list of things left to do.

**Comment by mmhat** [comment]
> [ ] Move the `Resource` effect to the `effectful-resourcet` package.

I suggest to move the `Resource` effect to the https://github.com/Kleidukos/effectful-contrib repository since it is not as ubiquitous as the other effects in this repository.

**Comment by mmhat** [comment]
Can we add some more documentation on Unlifting Strategies to the list?
My impression is that the concept should be laid out in a more prominent place since most people coming from something like `MonadUnliftIO` are used to pass the `runInIO` callback around without having to care about thread boundaries.
I wrote a little bit in https://github.com/ambroslins/effectful-contrib/pull/2 but I don't think it is as accurate as it could be.

**Comment by arybczak** [comment]
> Can we add some more documentation on Unlifting Strategies to the list?

Hmm, I'd say the haddock for `UnliftStrategy` is pretty informative. Can you point out what's missing? Even if someone misuses `MonadUnliftIO` with `SeqUnlift`, they'll get a runtime error pointing them to `ConcUnlift`.

The problem in the PR you linked to is that `unsafeUnliftIO` was used, which, as the name suggests is unsafe and the warning about why this function is unsafe was ignored/not understood, so perhaps this one would benefit from further explanation.

**Comment by mmhat** [comment]
The Haddock of UnliftStrategy is indeed good! What I had in mind when I wrote the comment above was more something at an introductory level. Right now the Haddock of the `Effectful` module (the one people probably look first ?) reads:

> Unlifting strategies
> data UnliftStrategy
> The strategy to use ...

I think it would be nice if there was a short introduction to what a unlifting strategy is and why we should care between the section title and the Haddock of UnliftStrategy. I.e. something between https://github.com/haskell-effectful/effectful/blob/cc25dc9ef4d06c8df391ede07642d3bbfbab6aca/effectful-core/src/Effectful.hs#L28 and the following line.

**Comment by arybczak** [comment]
Finally! Only took a year :slightly_smiling_face:  :tada:

**Comment by ocharles** [comment]
Wow, congratulations!!!
