### ISSUE TITLE
Getting started documentation

### ISSUE THREAD

**Issue by noughtmare** [haskell-effectful/effectful#215]
I wanted to quickly write an example of a handler in an effect system and I have been recommending effectful, so I thought why not use that in the example.

So, I opened up Hackage and went to the effectful package. The first problem I noticed is that it has no documentation for the `Effectful` module. That's unfortunate, but the description does say that you can go to the effectful-core package to view that documentation.

[There](https://hackage.haskell.org/package/effectful-core-2.3.0.1/docs/Effectful.html) I find a nice introduction which almost has what I need:

> The library provides:
> 
> *    The [Eff](https://hackage.haskell.org/package/effectful-core-2.3.0.1/docs/Effectful.html#t:Eff) monad that tracks effects at the type level. This is going to be the main monad of your application.
> *    A set of predefined, basic effects such as [Error](https://hackage.haskell.org/package/effectful-core-2.3.0.1/docs/Effectful-Error-Static.html#t:Error), [Reader](https://hackage.haskell.org/package/effectful-core-2.3.0.1/docs/Effectful-Reader-Static.html#t:Reader), [State](https://hackage.haskell.org/package/effectful-core-2.3.0.1/docs/Effectful-State-Static-Local.html#t:State) and [Writer](https://hackage.haskell.org/package/effectful-core-2.3.0.1/docs/Effectful-Writer-Static-Local.html#t:Writer).
> *    Utilities for defining new effects and interpreting them, possibly in terms of already existing ones.

That last bullet point is exactly what I need, but alas, it does not link to further explanation.

That hackage documentation seems like a dead end.

At this point I backtracked and went to the readme here on GitHub, but the only relevant part seems to be the links to examples:

> For the examples see the Introduction sections of [Effectful.Dispatch.Dynamic](https://hackage.haskell.org/package/effectful-core/docs/Effectful-Dispatch-Dynamic.html) and [Effectful.Dispatch.Static](https://hackage.haskell.org/package/effectful-core/docs/Effectful-Dispatch-Static.html).

I guess I could look at that, but I'd have to make a choice between Dynamic or Static effects which puts me off.

So, I'd suggest:

* Add links in that first "The library provides:" section of the main documentation.
* Choose either Dynamic or Static to be the default and first introduction and write a focused "getting started" documentation for that.

But I'm open for other ideas.

**Comment by arybczak** [comment]
> That last bullet point is exactly what I need, but alas, it does not link to further explanation.

Isn't what you want above the bullet list? :thinking: 

![doc screenshot](https://github.com/haskell-effectful/effectful/assets/387658/6df19cea-c87f-401f-8d92-dd308b75b4e9)

**Comment by arybczak** [comment]
> Choose either Dynamic or Static to be the default and first introduction and write a focused "getting started" documentation for that.

Yeah, I can add a note that when in doubt, start with dynamic dispatch. Especially since there will be some upcoming changes to `Effectful.Labeled` that make it very easy/efficient to work with dynamic labeled effects.

**Comment by arybczak** [comment]
I've put a PR that should fix this. @noughtmare can you have a look?
