### ISSUE TITLE
Is there "raiseUnder"?

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-effectful/effectful#217]
effectful has `raise :: Eff es r -> Eff (e : es) r`, for putting an unused effect on the top of the stack. Is there something that will put an unused effect in the second place? That is

```.hs
raiseUnder :: Eff (e : es) r -> Eff (e : e' : es) r
```

**Comment by ocharles** [comment]
I think `inject` can do this - does that work?

**Comment by tomjaguarpaw** [comment]
Perfect, thanks!
