### ISSUE TITLE
`INCOHERENT` instance causes unpredictable type inference

### ISSUE THREAD

**Issue by michaelpj** [haskell-effectful/effectful#227]
I came across a type inference wobble when using `effectful` with `OverloadedRecordDot`. See the GHC issue for details: https://gitlab.haskell.org/ghc/ghc/-/issues/25070

The diagnosis seems to be that the root cause is that the `INCOHERENT` pragmas on the instances for `Subset`/`KnownPrefix`. I'm sure those would have been avoided if possible, but it's perhaps helpful to have a concrete example of the cost. Maybe we can think again if they're avoidable?

**Comment by michaelpj** [comment]
I've spent a while looking at how `Subset` works and it's very clever. I can't see a way to make it work without the `INCOHERENT`, since it really wants a way to do something different when it gets to uninstantiated type variables, which is exactly the sort of thing GHC gets fussy about with merely overlapping instances.

(Perhaps a better type-wizard can see a way!)

I wonder if we could have a different function like
```
class KnownEffects es => SubsetKnown es xs
injectKnown :: (SubsetKnown xs es) => Eff xs a -> Eff es a
```
I think it should be possible to define that without any incoherence because it can just walk down the known list. But perhaps it's too narrow. I currently find myself wanting to inject `Eff`s with fixed lists of known effects, but maybe I'll want something different later...

**Comment by arybczak** [comment]
As you already noticed, incoherence is unfortunately necessary for `inject` to work in full generality. However, looks like in your specific case `KnownSubset` can be a trivial wrapper class to solve your problem as the following compiles:

```haskell
class Subset xs es => KnownSubset xs es
instance KnownSubset '[] es
instance (e :> es, KnownSubset xs es) => KnownSubset (e : xs) es

knownInject :: KnownSubset xs es => Eff xs a -> Eff es a
knownInject = inject

data Test = Test { act :: Eff '[IOE] () }

test2 :: forall es . IOE :> es => Test -> Eff es ()
test2 t = knownInject (t.act)
```

**Comment by michaelpj** [comment]
Ah, that's a nice trick, using the superclass constraints to force us into only using the coherent ways of solving `Subset`!

Would you be interested in having `knownInject` (under whatever name) in `effectful` as something to try if you have trouble with type inference? I don't know if it's generally useful enough.

**Comment by arybczak** [comment]
I'm not sure 🤔 it's a small addition, but it seems to be only useful when you work with fully monomorphic effect lists, which are generally discouraged. I guess you have a specific use case for this? Is it related to https://github.com/lexi-lambda/freer-simple/issues/30?

Will it ruin your day if you have to define `knownInject` yourself as a util for now?

**Comment by michaelpj** [comment]
So what we're doing is this: we have the usual "handle pattern", e.g.
```
data FooHandle = FooHandle { doIt :: Args -> IO () }

f :: IOE :> es ... => FooHandle -> Effs es ()
f h = do
  ...
  liftIO $ h.doIt args 
  ... 
```

This is fine. I wanted to make the handles have tracked effects. There are a few options:
- Handle fields have types like `forall es . (SomeEffect :> es) => Args -> Eff es ()`. This would be nicest, no need to use any kind of lifting function. But `OverloadedRecordDot` doesn't work with polymorphic fields.
- Handle fields have types like `Args -> Eff [SomeEffect] ()`. This would work with you just calling `inject`, which is comparably annoying to the current need to `liftIO`. But it doesn't work because of this issue.
    - We might define `injectKnown`, but it's not necessarily obvious that you need it, which will be annoying for devs.

So overall it's a somewhat annoying little corner where we're quite constrained by `OverloadedRecordDot`. I was really hoping that I could just somehow fix `inject` to work, but I think we might just leave it the way it is for now. If we really want to make the handlers use `Eff` we can go the `injectKnown` route.

**Comment by evanrelf** [comment]
I wonder if this would suffice?

```haskell
data FooHandle es = FooHandle { doIt :: IOE :> es => Args -> Eff es () }

f :: IOE :> es ... => FooHandle -> Effs es ()
f h = do
  ...
  liftIO $ h.doIt args 
  ...
```

**Comment by michaelpj** [comment]
That also works, but:
- You need to commit to the set of `es` when you _create_ the handle, which is annoying and in some sense much stronger than you need.
- You then need to pass lots more type variables around and make sure they line up.
- If you need to use the handle with two different `es` (I don't know if we do!) then you're going to be annoyed.

**Comment by arybczak** [comment]
@michaelpj to be honest, this is somewhat peculiar scenario.

"The" way would be to convert the `FooHandle` into an effect, then `foo` becomes the operation and everything falls into place (and if you have multiple FooHandleS, tag it with additional type parameter).

Using handles with fields polymorphic in `es` would also somewhat work, but you want to use `OverloadedRecordDot`which doesn't work with them. Also, calling `inject` every time you're calling your effectful operations isn't ideal. It's not very expensive, but not free either.

I'll not question your choices since I'm sure you have your reasons for sticking with this design, but under these conditions using effectful might not be worth it.

**Comment by michaelpj** [comment]
I agree it's a bit odd! And we are clearly making our lives more difficult - e.g. by really wanting to access the fields with `OverloadedRecordDot`. I definitely don't think this is worth making extreme efforts to support, but I think it's mildly interesting in that it's a real example of the `INCOHERENT` biting us, which might happen in other weird cases too. Or I guess I had a faint hope that someone might come up with a truly brilliant workaround :)

> "The" way would be to convert the FooHandle into an effect

It would simplify things a lot to make the handle into an effect. However, I think they aren't that well suited to that, because they really are "handles": there will be multiple of them, potentially an unknown number determined at runtime, so while we could use labelled effects that would be quite awkward. With value-level handles we can just stick them in a list, no problem.

> I'll not question your choices since I'm sure you have your reasons for sticking with this design, but under these conditions using effectful might not be worth it.

We definitely don't want to stop using `effectful`, we use it very heavily throughout the whole codebase, it's great! It's just this wrinkle is annoying at the moment, but we can certainly work around it.

**Comment by ocharles** [comment]
I'm working with @michaelpj on this project and the conclusion that "you're holding it wrong" is kind of what I expected. What I think could be interesting for us is to explore the non-handle approach and if that's not ergonomic see if we can improve that space. It ultimately might be more productive, and we haven't actually tried labelling these effects - maybe it's not as bad as we think!

**Comment by arybczak** [comment]
You can also keep `OverloadedRecordDot`, but you need to write instances yourself (or write a TH utility function for generating them):

```haskell
import Effectful
import GHC.Records

data Foo = Foo { _act :: forall es. IOE :> es => () -> Eff es () }
data Bar = Bar { _act :: forall es. IOE :> es => Eff es () }

instance
  (HasField "act" Foo a
  , IOE :> es
  , a ~ (() -> Eff es ())
  ) => HasField "act" Foo a where
  getField Foo{..} = _act

instance
  (HasField "act" Bar a
  , IOE :> es
  , a ~ Eff es ()
  ) => HasField "act" Bar a where
  getField Bar{..} = _act

test :: IOE :> es => Foo -> Bar -> Eff es ()
test foo bar = do
  foo.act ()
  bar.act
```

If the instance context looks peculiar to you, that's because including the instance head in the context is a somewhat dirty trick that lets you ignore the coverage condition.

**Comment by michaelpj** [comment]
> If the instance context looks peculiar to you, that's because including the instance head in the context is a somewhat dirty trick that lets you ignore the coverage condition.

OMG. I tried this and I did not figure out this particular evil trick. I bow to your knowledge of the typeclass resolution system, although I admit that I'm amazed that's allowed. I'm unsure if I'm willing to write (or generate) all those instances, but it's a cool trick indeed.

**Comment by arybczak** [comment]
I guess this can be closed?

**Comment by michaelpj** [comment]
Yes, I think there's nothing for `effectful` to do here.

**Comment by arybczak** [comment]
Since lend/borrow was adjusted to take a list of effects because of #233 and it needed addition of `KnownSubset` to work, perhaps it would be good to actually add `injectKnown` :thinking:  Does that still benefit your case?

**Comment by michaelpj** [comment]
Maybe? I'm actually coming back to this and I think I may just argue for us to bite the bullet and give up on `OverloadedRecordDot` here. 

Is it a problem for `lend`/`borrow`? I thought the only reason there was a problem here was the unusual functional dependencies from `HasField`?

**Comment by arybczak** [comment]
No, for lend/borrow the problem is that the subset should really be statically known. In theory you can write something like `localSeqBorrow @localEs` and get a `Eff (localEs ++ handlerEs)`, but then `++` doesn't reduce, GHC is not smart enough to realize that `x :> localEs` implies `x :> (localEs ++ handlerEs) and complains, which is not great UX.

Ok, I'll refrain from adding `injectKnown` for now then ;)
