### ISSUE TITLE
Reorder the type parameters of "raise"?

### ISSUE THREAD

**Issue by torgeirsh** [haskell-effectful/effectful#281]
Currently, the order is implicitly given by the type signature

> raise :: Eff es a -> Eff (e : es) a

which makes the order _es_, _a_, _e_. When using TypeApplications, I've found it more useful to specify a type for _e_ than the other two, so I wonder if adding an explicit forall keyword would make the function more ergonomic? For example:

> raise :: forall e es a. Eff es a -> Eff (e : es) a

**Comment by arybczak** [comment]
Sounds good, I opened a PR. I wonder when do you need to specify it though, consider it should always be unambiguous :thinking:

**Comment by torgeirsh** [comment]
I think it was due to having two different Error constraints on an effect list, and wanting to raise one of them, or something in that direction. Type inference generally seems less robust when dealing with constraints than regular types.
