### ISSUE TITLE
`localUnlift` allows doing `unsafeDupablePerformIO` to some extent

### ISSUE THREAD

**Issue by re-xyr** [haskell-effectful/effectful#42]
```haskell
data Hole :: Effect where
  Perform :: m a -> Hole m a

runHole = interpret \env -> \case
  Perform m -> localSeqUnlift env \unlift -> pure $ runPureEff $ unlift m
--                                           ^^^^^^^^^^^^^^^^^
```

Is this a problem?

**Comment by arybczak** [comment]
How is this `unsafeDupablePerformIO`?

**Comment by re-xyr** [comment]
I’ve thought for a while. Maybe we can store some metadata as a typeclass, like `Base es => EffectHandler e es` and then constrain the `localUnlift/Lift` functions to only unlift to/lift from the `es` that `Base` specifies (since that is perhaps the only moral usage). We can reflect that thing away in internal functions. Not sure if this hurts performance.
