### ISSUE TITLE
A way to embed existing monads

### ISSUE THREAD

**Issue by sproott** [haskell-effectful/effectful#63]
Maybe I'm missing something obvious, but I haven't found a way to use existing monads apart from IO. In polysemy, they have the Embed effect. Is this already possible, or if not, could it be implemented?

For context: I would like to use this e.g. for my XMonad config (might be overkill, I know). I need to embed the X monad, which is an alias for a Reader/State transformer stack.

**Comment by arybczak** [comment]
> Is this already possible, or if not, could it be implemented?

Unfortunately, no and no.

The `Eff` monad's underlyring representation has to be fully monomorphic, otherwise the performance gets out the window.

**Comment by arybczak** [comment]
What can be done in such cases is bypassing the monad in question, using effects equivalent to the transformers used there and then at the end injecting the monadic state back (if it changed).

So in case of the X monad

```haskell
r <- Mtl.ask
s <- Mtl.get
(a, s') <- liftIO . runEff . runState s . runReader r $ do
  -- do whatever you want here
Mtl.put s'
```

something like this.

**Comment by sproott** [comment]
Nice, I also noticed I can do the inverse of this:

```hs
liftX :: [Reader XConf, State XState, IOE] :>> es => X a -> Eff es a
liftX x = do
  r <- Reader.ask
  s <- State.get
  (a, s') <- liftIO $ runX r s x
  State.put s'
  pure a
```

So it actually seems possible to do this. Again, probably will not do this, but it's nice to know it's somehow possible.

I suppose this can be closed now?
