### ISSUE TITLE
Separate programs and handling to different files in benchmark?

### ISSUE THREAD

**Issue by re-xyr** [haskell-effectful/effectful#64]
I noticed that in effectful's benchmark suite, the programs and their handling are in the same file. As Alexis have mentioned, doing so can make GHC inline more aggressively and skew the results, making them less indicative of the performance characteristics in practice. Shall we move them to separate files?

**Comment by arybczak** [comment]
This is not necessary. See https://github.com/haskell-effectful/effectful/blob/ba4798f1eb540d9b4d13a3463f79ce0633cbb656/benchmarks/README.md:

> Moreover, the benchmarked code was annotated with NOINLINE pragmas to prevent GHC from inlining it and/or specializing away type class constraints related to effects. This is crucial in order to get realistic results, as for any non-trivial, multi-module application the compiler will not be able to do this as that would essentially mean performing whole program specialization.

That's the same thing splitting functions in separate files does.

**Comment by re-xyr** [comment]
Oh yes they do... guess I somehow overlooked them.
