### ISSUE TITLE
Exploring Koka-like effects and terminology 

### ISSUE THREAD

**Issue by Kleidukos** [haskell-effectful/effectful#65]
I was reading about[ Koka's effect system](https://koka-lang.github.io/koka/doc/book.html#why-effects):

```
fun sqr    : (int) -> total int       // total: mathematical total function    
fun divide : (int,int) -> exn int     // exn: may raise an exception (partial)  
fun turing : (tape) -> div int        // div: may not terminate (diverge)  
fun print  : (string) -> console ()   // console: may write to the console  
fun rand   : () -> ndet int           // ndet: non-deterministic  
```

> A function without any effect is called [total](https://koka-lang.github.io/koka/doc/std_core.html#type_space_total) and corresponds to mathematically total functions – a good place to be. Then we have effects for partial functions that can raise exceptions ([`exn`](https://koka-lang.github.io/koka/doc/std_core.html#type_space_exn)), and potentially non-terminating functions as [`div`](https://koka-lang.github.io/koka/doc/std_core_types.html#type_space_div) (divergent). The combination of `exn` and  `div` is called [`pure`](https://koka-lang.github.io/koka/doc/std_core.html#type_space_pure) as that corresponds to Haskell's notion of purity. On top of that we find mutability (as [st](https://koka-lang.github.io/koka/doc/std_core_types.html#type_space_st)) up to full non-deterministic side effects in [io](https://koka-lang.github.io/koka/doc/std_core.html#type_space_io).

I think it could be interesting to provide such things and, even though we can't possibly cover the entirety of the Haskell language, provide ways to lift such functions to these Effects.

@arybczak @mmhat What do you think about this? Could we try and explore putting something like the `Total`, `Divergent` and `Exception` effects?

**Comment by arybczak** [comment]
While this might make sense in Koka, in Haskell it doesn't, because anything can throw at any time. Also, any thread can receive asynchronous exception at any time.

`Eff` always has `MonadThrow`, `MonadCatch` and `MonadMask` available for that reason. You can think of it as an `Exception` effect that's always implicitly on.

**Comment by Kleidukos** [comment]
Haha, I had forgotten about asynchronous exceptions! Thank you!

**Comment by arybczak** [comment]
Similarly, in Haskell everything is `Divergent` and nothing is `Total`. So Haskell doesn't really fit this model 👻

**Comment by mmhat** [comment]
I agree with @arybczak , but I think a `Console` effect might be a good thing to have. For example, when looking at the signatures of
```haskell
foo1 :: Console :> es => Eff es ()
foo1 = Effectful.Console.putStrLn "Hello"

foo2 :: IOE :> es => Eff es ()
foo2 = liftIO $ putStrLn "Hello"
```
the first one is a bit more honest wrt. what it is actually doing. This effect might be something between a `Logging` and no output at all. Although it has a different purpose the [Trace](https://hackage.haskell.org/package/polysemy-1.7.1.0/docs/Polysemy-Trace.html) effect of polysemy might be similar.
