### ISSUE TITLE
Lens and/or optics usage with state

### ISSUE THREAD

**Issue by steffenomak** [haskell-effectful/effectful#81]
Hi, I'm playing around with this library and find it quite well documented and ease to use.

I'm building a statistics tool at work, where I'm using the state effect in some places and using the Xlsx package to generate reports.

I like the .= and other operators that work on inside the state monad. So my question is, how would one go about integrating the two? Should I re implement the operators I want? Or is there a more elegant solution?

**Comment by arybczak** [comment]
Hey. There's https://github.com/haskell-effectful/effectful-contrib/pull/24 - I'll put it in a package soon.

**Comment by steffenomak** [comment]
Nice thanks, so my thought about re implemetning them was the "correct" thought.

Thanks for the help.
