### ISSUE TITLE
CallStack loss when re-throwing errors

### ISSUE THREAD

**Issue by Elvecent** [haskell-effectful/effectful#83]
I'd like to be able to preserve original `throwError` locations when checking if an error was thrown.

```haskell
example :: (HasCallStack, Error () :> es) => Eff es ()
example = rethrowError throwsError
  where
    throwsError :: (HasCallStack, Error () :> es) => Eff es a
    -- call site is lost!
    throwsError = throwError ()
    rethrowError :: (HasCallStack, Error () :> es) => Eff es a -> Eff es a
    rethrowError m = do
      eres <- tryError m
      case eres of
        Right res  -> pure res
        -- discarded here
        Left (_,e) -> throwError e
```

Compare to `Control.Exception.try`:

```haskell
example' :: HasCallStack => IO ()
example' = rethrowError throwsError
  where
    throwsError :: HasCallStack => IO a
    -- call site preserved
    throwsError = error "oops"
    rethrowError :: HasCallStack => IO a -> IO a
    rethrowError m = do
      eres <- try @ErrorCall m
      case eres of
        Right res -> pure res
        -- no callstack modification here
        Left e    -> throw e
```

**Comment by arybczak** [comment]
When you rethrow, you need to do something like this:

```haskell
    Left (cs, e) -> let ?callStack = cs in throwError e
```

Can you check if that fixes the issue?

**Comment by Elvecent** [comment]
> Can you check if that fixes the issue?

This helps indeed, except I'm not sure if depending on this implementation detail is a good idea.

> Btw, if you plan to rethrow the same error, you probably don't want to catch it manually, but use something like `finally`

Yes, I thought that perhaps it would be nice to have something like `finally` for `effectful` errors?

**Comment by arybczak** [comment]
Please read introduction of https://hackage.haskell.org/package/effectful-core/docs/Effectful-Error-Static.html - you can see that `finally` from `Control.Exception.Catch` works as expected.

**Comment by Elvecent** [comment]
Oh... my bad. Big thanks!
