### ISSUE TITLE
Changing types of the Reader effect?

### ISSUE THREAD

**Issue by mmhat** [haskell-effectful/effectful#9]
I try to port one of my applications to this library and I can't figure out how to change the type of the Reader effect. All functions of the Interpreter module end up eliminating an effect in some way, i.e. `Eff (e ': baseEs) a -> Eff baseEs a`, but require the remaining effects to be the same (i.e. baseEs). Is there an easy way to write a transformation similar to `(e1 -> e1) -> Eff (e1 ': baseEs) a -> Eff (e2 ': baseEs) a`?

In particular, I need to replace [mapRIO](https://hackage.haskell.org/package/rio-0.1.20.0/docs/RIO.html#v:mapRIO).

**Comment by arybczak** [comment]
Function to change types of reader shouldn't be a problem to add (I'm pretty sure local trivially generalizes if you adjust its type signature), but remapping effects like `(e1 -> e1) -> Eff (e1 ': baseEs) a -> Eff (e2 ': baseEs) a` is not possible to write in general.

**Comment by mmhat** [comment]
I'm fine if it can be done for the Reader effect. I think that would be very helpful for migrating applications using the ReaderT pattern.

**Comment by arybczak** [comment]
Can you try making a PR that generalizes `local`?

**Comment by mmhat** [comment]
I started looking into that and noticed that as well. As far as I understand it we need a type-changing version of 'Effectful.Internal.Env.unsafeStateEnv' which is a bit of a problem since changing the type of an environment which is shared with other interpreters will break those. Is that correct?

**Comment by arybczak** [comment]
Yes, or looks like it. In what situation are you using `mapRIO`? It seems that this function would be mostly used to "zoom in" on the environment locally.

**Comment by mmhat** [comment]
Apart from that I use it pretty often to adjust the type of the logging function. A simple example can be found [here](https://hackage.haskell.org/package/rio-0.1.20.0/docs/RIO.html#g:17).

**Comment by arybczak** [comment]
I think the issues here is that `RIO` encourages different program structure than mtl/effect style :thinking: 

When you do `mapRIO`, you focus on parts of your environment and use it in some functions.

That's exactly what an effect will most often be, some sort of read only (or read-write) state + associated operations.

So IIUC `mapRIO` usages should be translated into separating that piece of data you focus on and operations that need it and making it a separate effect.

**Comment by mmhat** [comment]
I totally agree with you. Honestly, when I opened this issue I didn't think that it was such a big deal. Of course, having something like `mapRIO` for the Reader effect would be nice, especially during the migration period. That's where I wanted to use something like that in the first place.

**Comment by Kleidukos** [comment]
For posterity, is there a handy way that we can suggest people when they have to replace the usage of a `withReaderT`? 

I'm thinking of wholesale replacing the Reader in the stack, but I have trouble visualising the combination of functions that would get me from

```haskell
Eff '[Reader State1, IOE, DB]
```
to

```haskell
Eff '[Reader State2, DB, IOE]
```

[My practical usecase](https://github.com/flora-pm/flora-server/pull/158/files#diff-5b13137b73d6146ff03dfd498abc416cbb316e2e52d2356cc030a977ad24096cL140-R159) is the injection of a Session in the environment Reader through a type-level mechanism provided by Servant, but I have no doubt this limitation will be hit fairly quickly by people transitioning to `effectful`.

**Comment by arybczak** [comment]
Ok, so you can do this:

```haskell
withReader :: (r -> r') -> Eff [Reader r', IOE] a -> Eff [Reader r, IOE] a
withReader f m = do
  r <- ask
  runReader (f r) $ inject m
```

Unfortunately that requires working in a monomorphic stack (at least at the point of calling this function).

Is that a good solution to your problem? Not sure, there might be something more idiomatic that's more effect-like (perhaps the code that requires admin permissions should just require additional effect?). But with this you can experiment.
