### ISSUE TITLE
Static effect with state constrained with a type class

### ISSUE THREAD

**Issue by Merivuokko** [haskell-effectful/effectful#92]
In Effectful, it does not seem to be possible to create functions that access state in a static effect if the state is constrained by a type class and the concrete state type does not appear directly in the function signature.

I could not find any documentation related to this, nor any examples.

I acknowledge there might be a problem in my code, but regardless of this being a limitation of Effectful or not, this behaviour (along with a solution) could be documented.

Below is a minimal sample – a random number generator effect definition that fails to compile with GHC 9.4.1.

It is possible to define `withGen` but it does not seem to be possible to use it.

The error message is:

    Could not deduce (R.RandomGen g0) from the context:
        (R.RandomGen g, Random g :> es, R.Uniform a)
    bound by the type signature for: uniform

```haskell

-- | Psuedo-random number generator effect
module RandomEffect (Random, runRandom, uniform) where

import Control.Monad ((>=>))
import Data.Bifunctor (second)
import Data.Kind (Type)
import Effectful
import Effectful.Dispatch.Static
import System.Random qualified as R

data Random (g :: Type) :: Effect
-- The kind signature is necessary, otherwise ghc complains:
--    Expected a type, but ‘g’ has kind ‘k’

type instance DispatchOf (Random g) = Static NoSideEffects
newtype instance StaticRep (Random g) = Random g

-- | Run a pseudo-random number generator effect. Return the latest value of the generator and the effect result.
runRandom :: R.RandomGen g => g -> Eff (Random g : es) a -> Eff es (a, g)
runRandom gen = runStaticRep (Random $! gen) >=> pure . second (\(Random g) -> g)

-- | Call a function f with a generaor and put the returned gneerator back to
-- the effect.
withGen :: (R.RandomGen g, Random g :> es) => (g -> (a, g)) -> Eff es a
withGen f = do
    Random gen <- getStaticRep
    let (val, gen') = f gen
    putStaticRep $! Random $! gen'
    pure $! val

-- | Return a random value distributed uniformly across values of type a.
uniform :: (R.RandomGen g, Random g :> es, R.Uniform a) => Eff es a
uniform = withGen R.uniform
```

**Comment by arybczak** [comment]
It is possible, but you need to enable `AllowAmbiguousTypes` and then use `TypeApplications` when calling `uniform` to disambiguate which generator you want to use.

This is a generic restriction, not really specific to `effectful`.

**Comment by Merivuokko** [comment]
Ok, thank you very much.
