### ISSUE TITLE
Cannot run `Prim` effect without invoking `IOE`

### ISSUE THREAD

**Issue by qrpnxz** [haskell-effectful/effectful#93]
`Prim` currently has me either announcing I used `Prim`, or worse, if I try to get rid of `Prim`, say I'm doing arbitrary `IO`. I would like to be able to use `Prim` without requiring the effect from callers.

Would this be possible?:

```hs
runPrim :: (forall s. Eff [Prim s : es] a) -> Eff es a
runPrimIO :: IOE :> es => Eff [Prim RealWorld : es] a -> Eff es a
```

**Comment by arybczak** [comment]
Unfortunately not. This doesn't work:

```haskell
data Prim s :: Effect

type instance DispatchOf (Prim s) = Static WithSideEffects
data instance StaticRep (Prim s) = Prim

instance Prim s :> es => PrimMonad (Eff es) where
  type PrimState (Eff es) = s
  primitive = unsafeEff_ . IO . unsafeCoerce
```

because:

```
error:
    The RHS of an associated type declaration mentions out-of-scope variable ‘s’
      All such variables must be bound on the LHS
    |
310 |   type PrimState (Eff es) = s
```

To have Prim be `ST`-like `Eff` would have to be given additional type parameter. I experimented with this in the past, but decided against this as it has limited use, yet imposes a cost for everyone.

**Comment by qrpnxz** [comment]
I came up with something similar:

```hs
data STE s :: Effect

type instance DispatchOf (STE s) = Static NoSideEffects
data instance StaticRep (STE s) = STE

runSTE :: (forall s. Eff (STE s : es) a) -> Eff es a
runSTE eff = evalStaticRep STE eff

instance PrimMonad (Eff (STE s : es)) where
  type PrimState (Eff (STE s : es)) = s
  primitive = unsafeEff_ . IO . unsafeCoerce
```

I just haven't tested ergonomics yet in real code because overlapping with the current instance makes it a pain, but this should be pretty decent I think.

**Comment by qrpnxz** [comment]
I had an idea of a type family that we could put on the RHS that would match on any place on the layer stack, but have not tried it yet.

**Comment by arybczak** [comment]
> I just haven't tested ergonomics yet in real code because overlapping with the current instance makes it a pain, but this should be pretty decent I think.

There are two issues here:

1. It's not possible to use this with a typical/encouraged `STE s :> es => Eff es ()` pattern.
2. I'm pretty sure that usage of associated functions will be very annoying (i.e. require a lot of type annotations) without `effectful-plugin`.
3.

**Comment by qrpnxz** [comment]
I've successfully spliced `effectful-core` into my project with the modified `Prim` and it works like a charm. Nothing in my code requires both `Prim` and something else to be first, so there's no problem. Now that I think about it, `Prim` would have had to be first regardless because i wanted to run the effect and even the current `runPrim` requires `Prim` to be first in that case.

Where there could be a problem is if you wanted to run some other effect that depends on a prim object. Like say pass a mutable prim vector into the handler of an effect. So there's a trade-off. I was racking my brain about how to be able to just have both and be able to switch between them picking the trade-off and this came to me:

```hs
-- ^ ... Prim effect as we have now.
-- New STE effect as above, with no associated PrimMonad instance.
-- Then...
stToEff :: STE s :> es => ST s a -> Eff es a
stToEff = unsafeEff_ . IO . unsafeCoerce . internal
```

Epic. This covers a lot of uses, but I get this in my code:

```
    • Overlapping instances for Effectful.Prim.Prim s0
                                :> (Effectful.Prim.Prim s : es)
        arising from a use of ‘stToEff’
      Matching instances:
        instance (e :> es) => e :> (x : es)
          -- Defined in ‘Effectful.Internal.Effect’
        instance [overlapping] e :> (e : es)
          -- Defined in ‘Effectful.Internal.Effect’
      (The choice depends on the instantiation of ‘s0, s, es’
```

This isn't the first time I've ran into problems with these overlapping instances. I've got an idea or two about how we might improve the situation here, but for now I've got to add a type annotation.

I do consider this an improvement for the most part because now:

1. I can still use the current `Prim` (with the benefits that has).
2. I can use `STE` without modifying `effectful`. (Although to implement `primAsSTE` I need unexposed internals, that function may be utterly useless.)
3. I can put `STE` in any layer of the stack.

Where I lose some flexibility is now I can't pass `Eff (... : STE s : _) a` into a negative position as a `PrimMonad` (though I cannot remember an example of that). However, in this situation wrapping `Eff` in a `newtype` might not be awful? Will investigate.

I foresee that in cases where one wants to create and run prim ops in a localized area, `STE` will work like a charm, and in more complex cases with longer value lifetimes, `Prim` and `IOE` will become considerations.

---

Revised `STE`:
```hs
data STE s :: Effect
type instance DispatchOf (STE s) = Static NoSideEffects
data instance StaticRep (STE s) = STE

-- | Run an 'Eff' computation with primitive state-transformer actions purely.
runSTE :: (forall s. Eff (STE s : es) a) -> Eff es a
runSTE eff = evalStaticRep STE eff

-- | Lift a primitive state-transformer action with `STE`.
primToSTE
  :: (PrimBase m, STE s :> es, PrimState m ~ s)
  => m a -> Eff es a
primToSTE = unsafeEff_ . IO . unsafeCoerce . internal

-- | Lift a primitive state-transformer action with `Prim`.
primToEff
  :: (PrimBase m, Prim :> es, PrimState m ~ PrimState (Eff es))
  => m a -> Eff es a
primToEff = unsafeEff_ . IO . internal

-- | Lift a primitive state-transformer action with `IOE`.
primToIOE
  :: (PrimBase m, IOE :> es, PrimState m ~ RealWorld)
  => m a -> Eff es a
primToIOE = unsafeEff_ . IO . internal

-- Concrete variants omitted, but would be helpful when using
-- functions polymorphic on the `PrimMonad`.

-- | Interpret `Prim` as `STE`. (Most likely useless.)
primAsSTE :: STE (PrimState (Eff es)) :> es => Eff (Prim : es) a -> Eff es a
primAsSTE = evalStaticRep Prim

-- | Interpret `STE` as `Prim`.
steAsPrim :: Prim :> es => Eff (STE (PrimState (Eff es)) : es) a -> Eff es a
steAsPrim = evalStaticRep STE

-- | Interpret `STE` as `IOE`.
steAsIOE :: IOE :> es => Eff (STE RealWorld : es) a -> Eff es a
steAsIOE = evalStaticRep STE
```

**Comment by qrpnxz** [comment]
I've just noticed that some of the above are actually leaky (!). In fact, `Prim` is just inherently leaky:

```hs
ioToEff :: Prim :> es => IO a -> Eff es a
ioToEff = Control.Monad.Primitive.ioToPrim
```

**Comment by qrpnxz** [comment]
Actually, there is a solution. We need to do this:

```hs
```

**Comment by qrpnxz** [comment]
Created #94 to fix the above.

**Comment by arybczak** [comment]
> This isn't the first time I've ran into problems with these overlapping instances. I've got an idea or two about how we might improve the situation here, but for now I've got to add a type annotation.

This is the problem `effectful-plugin` solves (it's the second point I wrote [here](https://github.com/haskell-effectful/effectful/issues/93#issuecomment-1227831234)).

> While that fixes the leak, it occurred to me that you would lose the ability for Eff to act as IO with regards to PrimMonad (which you would reasonable want if you had IOE in scope).

That is absolutely fine, because then if your function has only `Prim :> es`, you cannot perform arbitrary IO, you need `IOE :> es` for that.

While supplying a distinct PrimState token seems like a good solution on the surface, as I mentioned in the associated PR I'm unsure about potential consequences.

**Comment by bradrn** [comment]
I’ve been thinking of using `effectful` to implement an algorithm requiring mutation; unfortunately, despite #94 and #95, `runPrim` still seems to require `IOE`. Has anyone else here had any further thoughts on getting @qrpnxz’s `runSTE` merged? Personally, I agree with @arybczak that disallowing arbitrary IO in `Prim :> es` would be absolutely fine, and indeed desirable.

**Comment by arybczak** [comment]
> I agree with @arybczak that disallowing arbitrary IO in Prim :> es would be absolutely fine, and indeed desirable.

This was done in #95.

> Unfortunately, despite https://github.com/haskell-effectful/effectful/pull/94 and https://github.com/haskell-effectful/effectful/pull/95, runPrim still seems to require IOE

This won't change, because if `Prim` didn't require `IOE`, you could do this:

```haskell
blah :: Int
blah =
  let v = runPureEff . runPrim $ newMutVar (0::Int)
      a = runPureEff . runPrim $ modifyMutVar v (+1) >> readMutVar v
      b = runPureEff . runPrim $ modifyMutVar v (*2) >> readMutVar v
  in a + b
```

and now if `a` is evaluated first, `blah` is `1 + 2 = 3` and if `b` is evaluated first, `blah` is `1 + 0 = 1`.

**Comment by bradrn** [comment]
> This won't change, because if `Prim` didn't require `IOE`, you could do this: …

Fair point… but surely there must be some way to stop the variable from escaping its scope, like `runST` does? If not, that would be a great pity; this would be a really useful effect to have.

**Comment by qrpnxz** [comment]
@bradrn I'm not sure either at the moment whether arybczak plans to add `STE` to `effectful` proper, but for now you can use https://hackage.haskell.org/package/effectful-st :smiley:

**Comment by arybczak** [comment]
@qrpnxz I created #98 as a demo for how you can get proper `STE` with `effectful`. You need to use `effectful-plugin` and rewrap most of the API of `primitive`, but it works.

**Comment by arybczak** [comment]
Since the original issue is solved, I'm closing this one. Please continue the discussion in #98.
