### ISSUE TITLE
Version of `base` (and perhaps other deps) is too liberal

### ISSUE THREAD

**Issue by qrpnxz** [haskell-effectful/effectful#97]
I've been informed by the Hackage people that the standard versioning scheme on Hackage is [PVP](https://pvp.haskell.org/). This includes `base`. Currently

- [ ] `effectful-core`
- [ ] `effectful`
- [ ] `effectful-th`
- [ ] `effectful-plugin`
- [ ] `resourcet-effectful`

and more are all having a range  like `>=4.13 && <5`. In PVP, the first two numbers of the version are *both* major versions, therefore these packages are allowing versions of `base` that may introduce breaking changes. Probably `>=4.13 && <4.18` will be the most appropriate correction.

I don't know if other dependencies have the same mistake. They should be checked. `cabal gen-bounds` and `cabal outdated` may help here.

Currently it appears that `effectful` is using something like [SemVer](https://semver.org/), but I could not find documented proof. `effectful` might want to align to the standard ecosystem versioning scheme, or otherwise definitely document what the versions are meaning.

**Comment by arybczak** [comment]
I'm liberal with upper bounds of `base` (and some other dependencies with stable api) since I'm too lazy to bump their bounds for all packages I maintain every time GHC is released.

**Comment by qrpnxz** [comment]
I don't have a counter to just not wanting to maintain the versions :sweat_smile:. I do find the issue fairly serious, so if you would like me to investigate myself and raise PRs I'll gladly do it.

Is `effectful` using SemVer, or PVP, or what, by the way?

**Comment by arybczak** [comment]
A lot of libraries use the `base <5` constraint, I've never seen it be a problem :thinking: 

> Is effectful using SemVer, or PVP, or what, by the way?

It uses PVP afaik.

**Comment by arybczak** [comment]
Closing, liberal upper bound of `base` has not historically been a problem and it reduces maintenance burden.
